#!/usr/bin/env bash
# Start the frontend (Vite) dev server.
# Usage: ./scripts/start-ui.sh [frontend_port] [backend_port]
# Defaults to ports based on worktree detection.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
DIR_NAME="$(basename "$REPO_DIR")"

# Port assignments per worktree
case "$DIR_NAME" in
    AgenticContextBuilder)     FRONTEND_PORT=5173; BACKEND_PORT=8000 ;;
    AgenticContextBuilder-wt1) FRONTEND_PORT=5174; BACKEND_PORT=8001 ;;
    AgenticContextBuilder-wt2) FRONTEND_PORT=5175; BACKEND_PORT=8002 ;;
    AgenticContextBuilder-wt3) FRONTEND_PORT=5176; BACKEND_PORT=8003 ;;
    *) echo "Unknown worktree: $DIR_NAME"; exit 1 ;;
esac

# Allow overrides via arguments
FE_PORT="${1:-$FRONTEND_PORT}"
BE_PORT="${2:-$BACKEND_PORT}"

# Kill any existing process on the port
if lsof -ti:"$FE_PORT" >/dev/null 2>&1; then
    echo "Killing existing process on port $FE_PORT..."
    kill -9 $(lsof -ti:"$FE_PORT") 2>/dev/null || true
    sleep 1
fi

echo "=== Frontend Server ==="
echo "Worktree:     $DIR_NAME"
echo "Frontend:     http://localhost:$FE_PORT"
echo "Backend API:  http://localhost:$BE_PORT"
echo "Press Ctrl+C to stop."
echo ""

cd "$REPO_DIR/ui"

# Install node deps if needed
if [ ! -d "node_modules" ]; then
    echo "Installing node dependencies..."
    npm install
fi

# Write .env so Vite picks up the ports
cat > .env <<EOF
# Worktree: $DIR_NAME
# Auto-generated by start-ui.sh - do not edit manually
VITE_PORT=$FE_PORT
VITE_API_PORT=$BE_PORT
EOF

export VITE_PORT="$FE_PORT"
export VITE_API_PORT="$BE_PORT"
npm run dev -- --host 0.0.0.0
