<#
.SYNOPSIS
    Start development servers for this worktree.

.DESCRIPTION
    Starts both backend (uvicorn) and frontend (vite) servers with the correct
    ports for this worktree. Each worktree has dedicated ports to avoid conflicts.
    Automatically creates/updates the ui/.env file with correct port configuration.

.PARAMETER BackendOnly
    Start only the backend server.

.PARAMETER FrontendOnly
    Start only the frontend server.

.PARAMETER Stop
    Stop any running dev servers for this worktree.

.PARAMETER Status
    Show status of dev servers without starting them.

.EXAMPLE
    .\scripts\start-dev.ps1
    # Starts both backend and frontend

.EXAMPLE
    .\scripts\start-dev.ps1 -Stop
    # Stops both servers

.EXAMPLE
    .\scripts\start-dev.ps1 -Status
    # Shows which servers are running
#>

param(
    [switch]$BackendOnly,
    [switch]$FrontendOnly,
    [switch]$Stop,
    [switch]$Status
)

# Detect which worktree we're in based on directory name
$repoDir = Split-Path -Parent $PSScriptRoot
$dirName = Split-Path -Leaf $repoDir

# Port assignments per worktree
$portConfig = @{
    "AgenticContextBuilder"     = @{ Backend = 8000; Frontend = 5173 }
    "AgenticContextBuilder-wt1" = @{ Backend = 8001; Frontend = 5174 }
    "AgenticContextBuilder-wt2" = @{ Backend = 8002; Frontend = 5175 }
    "AgenticContextBuilder-wt3" = @{ Backend = 8003; Frontend = 5176 }
}

# Get ports for this worktree
if (-not $portConfig.ContainsKey($dirName)) {
    Write-Error "Unknown worktree: $dirName. Expected one of: $($portConfig.Keys -join ', ')"
    exit 1
}

$backendPort = $portConfig[$dirName].Backend
$frontendPort = $portConfig[$dirName].Frontend

Write-Host "=== Dev Server Manager ===" -ForegroundColor Cyan
Write-Host "Worktree: $dirName" -ForegroundColor Yellow
Write-Host "Backend port: $backendPort" -ForegroundColor Yellow
Write-Host "Frontend port: $frontendPort" -ForegroundColor Yellow
Write-Host ""

# Ensure ui/.env file exists with correct ports
function Ensure-EnvFile {
    $envPath = Join-Path $repoDir "ui\.env"
    $envContent = @"
# Worktree: $dirName
# Auto-generated by start-dev.ps1 - do not edit manually
VITE_PORT=$frontendPort
VITE_API_PORT=$backendPort
"@

    $needsUpdate = $true
    if (Test-Path $envPath) {
        $currentContent = Get-Content $envPath -Raw
        if ($currentContent -eq $envContent) {
            $needsUpdate = $false
        }
    }

    if ($needsUpdate) {
        Set-Content -Path $envPath -Value $envContent -NoNewline
        Write-Host "Updated ui/.env with port configuration" -ForegroundColor Gray
    }
}

function Show-Status {
    Write-Host "=== Server Status ===" -ForegroundColor Cyan

    $backendRunning = Test-PortInUse $backendPort
    $frontendRunning = Test-PortInUse $frontendPort

    if ($backendRunning) {
        $procId = (Get-NetTCPConnection -LocalPort $backendPort -ErrorAction SilentlyContinue).OwningProcess | Select-Object -First 1
        Write-Host "Backend:  RUNNING on port $backendPort (PID: $procId)" -ForegroundColor Green
    } else {
        Write-Host "Backend:  NOT RUNNING (port $backendPort)" -ForegroundColor Red
    }

    if ($frontendRunning) {
        $procId = (Get-NetTCPConnection -LocalPort $frontendPort -ErrorAction SilentlyContinue).OwningProcess | Select-Object -First 1
        Write-Host "Frontend: RUNNING on port $frontendPort (PID: $procId)" -ForegroundColor Green
    } else {
        Write-Host "Frontend: NOT RUNNING (port $frontendPort)" -ForegroundColor Red
    }

    Write-Host ""
}

function Stop-ProcessTree {
    param([int]$ParentId)

    # Get all child processes recursively
    $children = Get-CimInstance Win32_Process | Where-Object { $_.ParentProcessId -eq $ParentId }
    foreach ($child in $children) {
        Stop-ProcessTree -ParentId $child.ProcessId
    }

    # Stop the parent
    Stop-Process -Id $ParentId -Force -ErrorAction SilentlyContinue
}

function Stop-PortProcess {
    param([int]$Port, [string]$Name)

    $maxAttempts = 3
    for ($i = 1; $i -le $maxAttempts; $i++) {
        $procId = (Get-NetTCPConnection -LocalPort $Port -ErrorAction SilentlyContinue).OwningProcess | Select-Object -First 1

        if (-not $procId) {
            Write-Host "$Name not running on port $Port" -ForegroundColor Gray
            return $true
        }

        Write-Host "Stopping $Name (PID: $procId, attempt $i)..." -ForegroundColor Gray

        # Try taskkill with tree first
        & taskkill /PID $procId /T /F 2>$null

        # Also try direct kill in case process is orphaned
        Stop-Process -Id $procId -Force -ErrorAction SilentlyContinue

        Start-Sleep -Milliseconds 500

        # Check if port is free now
        if (-not (Test-PortInUse $Port)) {
            Write-Host "$Name stopped." -ForegroundColor Green
            return $true
        }
    }

    Write-Host "Warning: Could not stop $Name on port $Port" -ForegroundColor Yellow
    return $false
}

function Stop-DevServers {
    Write-Host "Stopping dev servers..." -ForegroundColor Yellow

    $backendStopped = Stop-PortProcess -Port $backendPort -Name "Backend"
    $frontendStopped = Stop-PortProcess -Port $frontendPort -Name "Frontend"

    if ($backendStopped -and $frontendStopped) {
        Write-Host "All servers stopped successfully." -ForegroundColor Green
    }
}

function Test-PortInUse {
    param([int]$Port)
    $connection = Get-NetTCPConnection -LocalPort $Port -ErrorAction SilentlyContinue
    return $null -ne $connection
}

function Start-Backend {
    if (Test-PortInUse $backendPort) {
        Write-Host "Backend already running on port $backendPort" -ForegroundColor Green
        return
    }

    Write-Host "Starting backend on port $backendPort..." -ForegroundColor Cyan

    # Use cmd /c start to reliably open a new window across different shell contexts
    $backendCmd = "python -m uvicorn context_builder.api.main:app --reload --port $backendPort"
    $title = "Backend-wt1-$backendPort"
    Start-Process cmd -ArgumentList "/c", "title $title && cd /d `"$repoDir`" && $backendCmd" -WindowStyle Normal

    # Wait for startup
    Start-Sleep -Seconds 3
    if (Test-PortInUse $backendPort) {
        Write-Host "Backend started successfully" -ForegroundColor Green
    } else {
        Write-Host "Backend may still be starting..." -ForegroundColor Yellow
    }
}

function Start-Frontend {
    if (Test-PortInUse $frontendPort) {
        Write-Host "Frontend already running on port $frontendPort" -ForegroundColor Green
        return
    }

    Write-Host "Starting frontend on port $frontendPort..." -ForegroundColor Cyan

    # Use cmd /c start to reliably open a new window across different shell contexts
    # Set env vars and run npm dev
    $title = "Frontend-wt1-$frontendPort"
    $frontendCmd = "set VITE_PORT=$frontendPort && set VITE_API_PORT=$backendPort && npm run dev"
    Start-Process cmd -ArgumentList "/c", "title $title && cd /d `"$repoDir\ui`" && $frontendCmd" -WindowStyle Normal

    # Wait for startup
    Start-Sleep -Seconds 5
    if (Test-PortInUse $frontendPort) {
        Write-Host "Frontend started successfully" -ForegroundColor Green
    } else {
        Write-Host "Frontend may still be starting..." -ForegroundColor Yellow
    }
}

# Main logic
if ($Status) {
    Show-Status
    exit 0
}

if ($Stop) {
    Stop-DevServers
    exit 0
}

# Ensure .env file is correct before starting
Ensure-EnvFile

if (-not $FrontendOnly) {
    Start-Backend
}

if (-not $BackendOnly) {
    Start-Frontend
}

Write-Host ""
Write-Host "=== Servers Ready ===" -ForegroundColor Green
Write-Host "Backend:  http://localhost:$backendPort" -ForegroundColor Cyan
Write-Host "Frontend: http://localhost:$frontendPort" -ForegroundColor Cyan
Write-Host ""
Write-Host "Commands:" -ForegroundColor Gray
Write-Host "  Status: .\scripts\start-dev.ps1 -Status" -ForegroundColor Gray
Write-Host "  Stop:   .\scripts\start-dev.ps1 -Stop" -ForegroundColor Gray
