"""Claims router - endpoints for listing and reviewing claims."""

import json
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, HTTPException, Query

from context_builder.api.dependencies import (
    get_assessment_service,
    get_claims_service,
    get_data_dir,
    get_documents_service,
)
from context_builder.api.models import (
    ClaimReviewPayload,
    ClaimSummary,
    DocSummary,
    RunSummary,
)

router = APIRouter(tags=["claims"])


@router.get("/api/claims", response_model=List[ClaimSummary])
def list_claims(run_id: Optional[str] = Query(None, description="Filter by run ID")):
    """
    List all claims in the data directory.

    Args:
        run_id: Optional run ID to filter extraction metrics. If not provided, uses latest run.

    Uses new folder structure:
      {claim_id}/docs/{doc_id}/meta/doc.json
      {claim_id}/runs/{run_id}/extraction/{doc_id}.json
    """
    return get_claims_service().list_claims(run_id)


@router.get("/api/claims/runs")
def list_claim_runs():
    """
    List all available run IDs for the claims view.

    Returns list of run IDs sorted newest first, with metadata.
    Reads from global runs directory (output/runs/) when available.
    """
    return get_claims_service().list_runs()


@router.get("/api/claims/{claim_id}/docs", response_model=List[DocSummary])
def list_docs(claim_id: str, run_id: Optional[str] = Query(None, description="Filter by run ID")):
    """
    List documents for a specific claim.

    Args:
        claim_id: Can be either the full folder name or extracted claim number.
        run_id: Optional run ID for extraction metrics. If not provided, uses latest run.
    """
    return get_documents_service().list_docs(claim_id, run_id)


@router.get("/api/runs/latest", response_model=RunSummary)
def get_run_summary():
    """Get metrics summary across all claims."""
    return get_claims_service().get_run_summary()


@router.get("/api/claims/{claim_id}/review", response_model=ClaimReviewPayload)
def get_claim_review(claim_id: str):
    """
    Get claim review payload for the claim-level review screen.

    Returns claim metadata, ordered doc list with status, and prev/next claim IDs
    for sequential navigation.
    """
    return get_claims_service().get_claim_review(claim_id)


@router.get("/api/claims/{claim_id}/facts")
def get_claim_facts(claim_id: str) -> Optional[Dict[str, Any]]:
    """
    Get aggregated claim facts from the context folder.

    Returns the contents of claim_facts.json if it exists, or null if not.
    The file is generated by the claim aggregation pipeline.
    """
    data_dir = get_data_dir()
    facts_path = data_dir / claim_id / "context" / "claim_facts.json"

    if not facts_path.exists():
        return None

    try:
        with open(facts_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError) as e:
        raise HTTPException(status_code=500, detail=f"Error reading claim facts: {e}")


@router.get("/api/claims/{claim_id}/assessment")
def get_claim_assessment(claim_id: str) -> Optional[Dict[str, Any]]:
    """
    Get claim assessment from the context folder.

    Returns the transformed assessment matching the frontend ClaimAssessment type,
    or null if no assessment exists. Transforms backend format to frontend format:
    - assessment_timestamp -> assessed_at
    - payout.final_payout -> payout (number)
    - check_number "1b" -> 1 (parse to int)
    - assumptions[].confidence_impact -> assumptions[].impact
    """
    return get_assessment_service().get_assessment(claim_id)


@router.get("/api/claims/{claim_id}/assessment/history")
def get_claim_assessment_history(claim_id: str) -> List[Dict[str, Any]]:
    """
    Get assessment history for a claim.

    Currently returns the current assessment as a single history entry.
    Future versions may store and return multiple historical assessments.
    """
    return get_assessment_service().get_assessment_history(claim_id)


@router.get("/api/assessment/evals/latest")
def get_latest_assessment_eval() -> Optional[Dict[str, Any]]:
    """
    Get the latest assessment evaluation results.

    Reads the most recent assessment_eval_*.json file from the workspace
    eval directory and transforms it to match the frontend AssessmentEvaluation type.

    Returns:
        Transformed evaluation with confusion matrix, per-claim results, and
        summary metrics (accuracy, precision, refer rate). Returns null if
        no evaluation files exist.
    """
    return get_assessment_service().get_latest_evaluation()
